version: '3.3'

services:
  db:
    container_name: game_postgres
    image: postgres
    
    environment:
      POSTGRES_DB: "game"
      POSTGRES_USER: "game_user"
      POSTGRES_PASSWORD: "game_pwd"

    ports:
      - 5432:5432
